### ISSUE TITLE
Uma dúvida das listas (L2 Q2)

### ISSUE THREAD

**Issue by wellington36** [isaquepim/tutoring#1]
@isaquepim, Da lista 2 tem essa questão:

![image](https://user-images.githubusercontent.com/61877847/186802126-0d6e29b9-b979-4562-95d8-b650fa65f876.png)

Só que não estou pegando o que está faltando nisso:

$$
  \begin{align}
    P(X_0 = i_0 \mid X_1 = i_1, \ldots, X_n = i_n) &= \frac{P(X_0 = i_0,X_1 = i_1, \ldots, X_n = i_n)}{P(X_1 = i_1, \ldots, X_n = i_n)} \\
    &= ... \\
    &= \frac{P(X_0 = i_0, X_1 = i_1)}{P(X_1 = i_1)}
  \end{align}
$$

**Comment by isaquepim** [comment]
É isso aí mesmo! Agora da mesma forma que usou a nossa atual definição de probabilidade condicional para começar a questão, use ela para terminá-la.

$$P(A|B) = \frac{P(A , B)}{P(B)} $$

$$\frac{P(X_0 = i_0, X_1 = i_1)}{P(X_1 = i_1)} = P(X_0 = i_0| X_1 = i_1)$$

Ou a dúvida era  o $\dots$?

**Comment by wellington36** [comment]
Sim, era o " $\ldots$ " na verdade.

**Comment by isaquepim** [comment]
Ok. A ideia para simplificar isso é decompor essa probabilidade e usar a propriedade de Markov.

$$ P(X_0, X_1, \dots, X_n) = P(X_n| X_{n-1}, \dots, X_1, X_0)P(X_{n-1}|X_{n-2}, \dots, X_1,X_0) \dots P(X_1|X_0)P(X_0)$$

$$ \overset{Markov}{=} P(X_n|X_{n-1})P(X_{n-1}|X_{n-2})\dots P(X_1|X_0)P(X_0)$$

Se fizer isso em cima e embaixo vai ver que vários termos cancelam e chega no resultado desejado. Acho que isso fecha.
